secrets:
  cloudflare-token:
    file: ./secrets/cloudflare-token.secret
  cloudflare-email:
    file: ./secrets/cloudflare-email.secret

services:
  traefik:
    container_name: traefik
    image: traefik:v3.6.2
    security_opt:
      - no-new-privileges:true # Renforce la sécurité en empêchant l'élévation de privilèges dans le conteneur.
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - "cloudflare-token"
      - "cloudflare-email"
    environment:
      - "CF_DNS_API_TOKEN_FILE=/run/secrets/cloudflare-token" # Utilise un secret Docker pour stocker le token API Cloudflare de manière sécurisée.
      - "CF_API_EMAIL_FILE=/run/secrets/cloudflare-email" # Utilise un secret Docker pour stocker l'email Cloudflare de manière sécurisée.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic:/etc/traefik/dynamic:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./certs:/letsencrypt
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"

      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`traefik.{{domain.name}}`)" # Remplacer {{domain.name}} par votre nom de domaine
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal" # Utilise le service interne de l'API Traefik pour le dashboard
      - "traefik.http.routers.dashboard.tls=true"

      # Basic‑auth middleware
      - "traefik.http.middlewares.dashboard-auth.basicauth.users={{hashed_user}}" # Remplacer {{hashed_user}} par l'utilisateur et le mot de passe haché
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"

  # Whoami application
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.{{domain.name}}`)" # Remplacer {{domain.name}} par votre nom de domaine
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"

networks:
  proxy:
    name: proxy